/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UltimaColheitaRouteImport } from './routes/ultima-colheita'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BiomerendaRouteImport } from './routes/biomerenda'
import { Route as AguaRouteImport } from './routes/agua'
import { Route as IndexRouteImport } from './routes/index'

const UltimaColheitaRoute = UltimaColheitaRouteImport.update({
  id: '/ultima-colheita',
  path: '/ultima-colheita',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BiomerendaRoute = BiomerendaRouteImport.update({
  id: '/biomerenda',
  path: '/biomerenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AguaRoute = AguaRouteImport.update({
  id: '/agua',
  path: '/agua',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agua': typeof AguaRoute
  '/biomerenda': typeof BiomerendaRoute
  '/dashboard': typeof DashboardRoute
  '/mercado': typeof MercadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ultima-colheita': typeof UltimaColheitaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agua': typeof AguaRoute
  '/biomerenda': typeof BiomerendaRoute
  '/dashboard': typeof DashboardRoute
  '/mercado': typeof MercadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ultima-colheita': typeof UltimaColheitaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agua': typeof AguaRoute
  '/biomerenda': typeof BiomerendaRoute
  '/dashboard': typeof DashboardRoute
  '/mercado': typeof MercadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ultima-colheita': typeof UltimaColheitaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agua'
    | '/biomerenda'
    | '/dashboard'
    | '/mercado'
    | '/sitemap.xml'
    | '/ultima-colheita'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agua'
    | '/biomerenda'
    | '/dashboard'
    | '/mercado'
    | '/sitemap.xml'
    | '/ultima-colheita'
  id:
    | '__root__'
    | '/'
    | '/agua'
    | '/biomerenda'
    | '/dashboard'
    | '/mercado'
    | '/sitemap.xml'
    | '/ultima-colheita'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AguaRoute: typeof AguaRoute
  BiomerendaRoute: typeof BiomerendaRoute
  DashboardRoute: typeof DashboardRoute
  MercadoRoute: typeof MercadoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UltimaColheitaRoute: typeof UltimaColheitaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ultima-colheita': {
      id: '/ultima-colheita'
      path: '/ultima-colheita'
      fullPath: '/ultima-colheita'
      preLoaderRoute: typeof UltimaColheitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biomerenda': {
      id: '/biomerenda'
      path: '/biomerenda'
      fullPath: '/biomerenda'
      preLoaderRoute: typeof BiomerendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agua': {
      id: '/agua'
      path: '/agua'
      fullPath: '/agua'
      preLoaderRoute: typeof AguaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AguaRoute: AguaRoute,
  BiomerendaRoute: BiomerendaRoute,
  DashboardRoute: DashboardRoute,
  MercadoRoute: MercadoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UltimaColheitaRoute: UltimaColheitaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
